services:
  db:
    image: postgres:18-alpine
    restart: always
    shm_size: '128mb'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
      - ./database/data:/var/lib/postgresql   # Persistent data storage

  interface:
    build: ./interface
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./interface:/app
      - ./pieces:/pieces
    environment:
      - FLASK=${FLASK_ENV}
    depends_on:
      - db

  nats:
    image: nats:latest
    container_name: nats_main
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - ./nats/nats.conf:/etc/nats/nats.conf
      - nats_data:/data/jetstream
    command: ["-c", "/etc/nats/nats.conf"]

  nats-client:
    image: natsio/nats-box
    container_name: nats_client
    restart: always
    depends_on:
      - nats
    entrypoint: /bin/sh
    tty: true

  platform:
    build: ./platform
    volumes:
      - ./platform:/platform
      - ./pieces:/pieces
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - nats

volumes:
  nats_data: